namespace EntityFrameworkCore.SqlServer.SimpleBulks
{
    public static class Constants
    {
        public const string AutoGeneratedIndexNumberColumn = "AutoGeneratedIndexNumberColumn";
        public const string Collation = "SQL_Latin1_General_CP1_CI_AS";
    }
}
