using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace EntityFrameworkCore.SqlServer.SimpleBulks.Extensions;

public static class IListExtensions
{
    public static DataTable ToDataTable<T>(this IReadOnlyCollection<T> data, IReadOnlyCollection<string> propertyNames, IReadOnlyDictionary<string, ValueConverter> valueConverters = null, bool addIndexNumberColumn = false, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var table = new DataTable() { MinimumCapacity = data.Count() };

        foreach (var propName in propertyNames)
        {
            cancellationToken.ThrowIfCancellationRequested();

            table.Columns.Add(propName, PropertiesCache<T>.GetPropertyUnderlyingType(propName, valueConverters));
        }

        if (addIndexNumberColumn)
        {
            table.Columns.Add(Constants.AutoGeneratedIndexNumberColumn, typeof(long));
        }

        long idx = 0;

        foreach (T item in data)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var row = table.NewRow();

            foreach (var propName in propertyNames)
            {
                cancellationToken.ThrowIfCancellationRequested();

                row[propName] = PropertiesCache<T>.GetPropertyValue(propName, item, valueConverters) ?? DBNull.Value;
            }

            if (addIndexNumberColumn)
            {
                row[Constants.AutoGeneratedIndexNumberColumn] = idx;
            }

            table.Rows.Add(row);

            idx++;
        }
        return table;
    }

    public static async Task<DataTable> ToDataTableAsync<T>(this IReadOnlyCollection<T> data, IReadOnlyCollection<string> propertyNames, IReadOnlyDictionary<string, ValueConverter> valueConverters = null, bool addIndexNumberColumn = false, CancellationToken cancellationToken = default)
    {
        return await Task.Run(() =>
        {
            return data.ToDataTable(propertyNames, valueConverters, addIndexNumberColumn, cancellationToken);
        }, cancellationToken);
    }
}
