// <auto-generated />
using System;
using System.Collections.Generic;
using DbContextExtensionsExamples;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbContextExtensionsExamples.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20260308062025_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbContextExtensionsExamples.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasDiscriminator().HasValue("Blog");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.ComplexOwnedTypeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ComplexShippingAddress", "DbContextExtensionsExamples.Entities.ComplexOwnedTypeOrder.ComplexShippingAddress#ComplexTypeAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Location", "DbContextExtensionsExamples.Entities.ComplexOwnedTypeOrder.ComplexShippingAddress#ComplexTypeAddress.Location#ComplexTypeLocation", b2 =>
                                {
                                    b2.Property<double>("Lat")
                                        .HasColumnType("float");

                                    b2.Property<double>("Lng")
                                        .HasColumnType("float");
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("ComplexOwnedTypeOrders");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.ComplexTypeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ShippingAddress", "DbContextExtensionsExamples.Entities.ComplexTypeOrder.ShippingAddress#ComplexTypeAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Location", "DbContextExtensionsExamples.Entities.ComplexTypeOrder.ShippingAddress#ComplexTypeAddress.Location#ComplexTypeLocation", b2 =>
                                {
                                    b2.Property<double>("Lat")
                                        .HasColumnType("float");

                                    b2.Property<double>("Lng")
                                        .HasColumnType("float");
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("ComplexTypeOrders");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.CompositeKeyRow", b =>
                {
                    b.Property<int>("Id1")
                        .HasColumnType("int");

                    b.Property<int>("Id2")
                        .HasColumnType("int");

                    b.Property<int>("Column1")
                        .HasColumnType("int");

                    b.Property<string>("Column2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Column3")
                        .HasColumnType("datetime2");

                    b.HasKey("Id1", "Id2");

                    b.ToTable("CompositeKeyRows");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.ConfigurationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id1")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Key1");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SeasonAsInt")
                        .HasColumnType("int");

                    b.Property<string>("SeasonAsString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfigurationEntries");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.JsonComplexOwnedTypeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ComplexShippingAddress", "DbContextExtensionsExamples.Entities.JsonComplexOwnedTypeOrder.ComplexShippingAddress#ComplexTypeAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Street");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Location", "DbContextExtensionsExamples.Entities.JsonComplexOwnedTypeOrder.ComplexShippingAddress#ComplexTypeAddress.Location#ComplexTypeLocation", b2 =>
                                {
                                    b2.Property<double>("Lat");

                                    b2.Property<double>("Lng");

                                    b2.HasJsonPropertyName("xxx");
                                });

                            b1.ToJson("ComplexShippingAddress");
                        });

                    b.HasKey("Id");

                    b.ToTable("JsonComplexOwnedTypeOrders");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.JsonComplexTypeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ShippingAddress", "DbContextExtensionsExamples.Entities.JsonComplexTypeOrder.ShippingAddress#ComplexTypeAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Street");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Location", "DbContextExtensionsExamples.Entities.JsonComplexTypeOrder.ShippingAddress#ComplexTypeAddress.Location#ComplexTypeLocation", b2 =>
                                {
                                    b2.Property<double>("Lat");

                                    b2.Property<double>("Lng");

                                    b2.HasJsonPropertyName("xxx");
                                });

                            b1.ToJson("ShippingAddress");
                        });

                    b.HasKey("Id");

                    b.ToTable("JsonComplexTypeOrders");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.JsonOwnedTypeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("JsonOwnedTypeOrders");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.OwnedTypeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("OwnedTypeOrders");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.Row", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Column1")
                        .HasColumnType("int");

                    b.Property<string>("Column2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Column3")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.RssBlog", b =>
                {
                    b.HasBaseType("DbContextExtensionsExamples.Blog");

                    b.Property<string>("RssUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("RssBlog");
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.ComplexOwnedTypeOrder", b =>
                {
                    b.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeAddress", "OwnedShippingAddress", b1 =>
                        {
                            b1.Property<int>("ComplexOwnedTypeOrderId")
                                .HasColumnType("int");

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ComplexOwnedTypeOrderId");

                            b1.ToTable("ComplexOwnedTypeOrders");

                            b1.WithOwner()
                                .HasForeignKey("ComplexOwnedTypeOrderId");

                            b1.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeLocation", "Location", b2 =>
                                {
                                    b2.Property<int>("OwnedTypeAddressComplexOwnedTypeOrderId")
                                        .HasColumnType("int");

                                    b2.Property<double>("Lat")
                                        .HasColumnType("float");

                                    b2.Property<double>("Lng")
                                        .HasColumnType("float");

                                    b2.HasKey("OwnedTypeAddressComplexOwnedTypeOrderId");

                                    b2.ToTable("ComplexOwnedTypeOrders");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedTypeAddressComplexOwnedTypeOrderId");
                                });

                            b1.Navigation("Location")
                                .IsRequired();
                        });

                    b.Navigation("OwnedShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.JsonComplexOwnedTypeOrder", b =>
                {
                    b.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeAddress", "OwnedShippingAddress", b1 =>
                        {
                            b1.Property<int>("JsonComplexOwnedTypeOrderId");

                            b1.Property<string>("Street");

                            b1.HasKey("JsonComplexOwnedTypeOrderId");

                            b1.ToTable("JsonComplexOwnedTypeOrders");

                            b1.ToJson("OwnedShippingAddress");

                            b1.WithOwner()
                                .HasForeignKey("JsonComplexOwnedTypeOrderId");

                            b1.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeLocation", "Location", b2 =>
                                {
                                    b2.Property<int>("OwnedTypeAddressJsonComplexOwnedTypeOrderId");

                                    b2.Property<double>("Lat");

                                    b2.Property<double>("Lng");

                                    b2.HasKey("OwnedTypeAddressJsonComplexOwnedTypeOrderId");

                                    b2.ToTable("JsonComplexOwnedTypeOrders");

                                    b2.HasJsonPropertyName("xxx");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedTypeAddressJsonComplexOwnedTypeOrderId");
                                });

                            b1.Navigation("Location")
                                .IsRequired();
                        });

                    b.Navigation("OwnedShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.JsonOwnedTypeOrder", b =>
                {
                    b.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeAddress", "ShippingAddress", b1 =>
                        {
                            b1.Property<int>("JsonOwnedTypeOrderId");

                            b1.Property<string>("Street");

                            b1.HasKey("JsonOwnedTypeOrderId");

                            b1.ToTable("JsonOwnedTypeOrders");

                            b1.ToJson("ShippingAddress");

                            b1.WithOwner()
                                .HasForeignKey("JsonOwnedTypeOrderId");

                            b1.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeLocation", "Location", b2 =>
                                {
                                    b2.Property<int>("OwnedTypeAddressJsonOwnedTypeOrderId");

                                    b2.Property<double>("Lat");

                                    b2.Property<double>("Lng");

                                    b2.HasKey("OwnedTypeAddressJsonOwnedTypeOrderId");

                                    b2.ToTable("JsonOwnedTypeOrders");

                                    b2.HasJsonPropertyName("xxx");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedTypeAddressJsonOwnedTypeOrderId");
                                });

                            b1.Navigation("Location")
                                .IsRequired();
                        });

                    b.Navigation("ShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("DbContextExtensionsExamples.Entities.OwnedTypeOrder", b =>
                {
                    b.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeAddress", "ShippingAddress", b1 =>
                        {
                            b1.Property<int>("OwnedTypeOrderId")
                                .HasColumnType("int");

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OwnedTypeOrderId");

                            b1.ToTable("OwnedTypeOrders");

                            b1.WithOwner()
                                .HasForeignKey("OwnedTypeOrderId");

                            b1.OwnsOne("DbContextExtensionsExamples.Entities.OwnedTypeLocation", "Location", b2 =>
                                {
                                    b2.Property<int>("OwnedTypeAddressOwnedTypeOrderId")
                                        .HasColumnType("int");

                                    b2.Property<double>("Lat")
                                        .HasColumnType("float");

                                    b2.Property<double>("Lng")
                                        .HasColumnType("float");

                                    b2.HasKey("OwnedTypeAddressOwnedTypeOrderId");

                                    b2.ToTable("OwnedTypeOrders");

                                    b2.WithOwner()
                                        .HasForeignKey("OwnedTypeAddressOwnedTypeOrderId");
                                });

                            b1.Navigation("Location")
                                .IsRequired();
                        });

                    b.Navigation("ShippingAddress")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
