using EntityFrameworkCore.SqlServer.SimpleBulks.Extensions;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Text;

namespace EntityFrameworkCore.SqlServer.SimpleBulks.BulkInsert
{
    public class BulkInsertBuilder<T>
    {
        private IEnumerable<T> _data;
        private string _tableName;
        private string _ouputIdColumn;
        private IEnumerable<string> _columnNames;
        private IDictionary<string, string> _dbColumnMappings;
        private BulkInsertOptions _options;
        private readonly SqlConnection _connection;
        private readonly SqlTransaction _transaction;

        public BulkInsertBuilder(SqlConnection connection)
        {
            _connection = connection;
        }

        public BulkInsertBuilder(SqlConnection connection, SqlTransaction transaction = null)
        {
            _connection = connection;
            _transaction = transaction;
        }

        public BulkInsertBuilder<T> WithData(IEnumerable<T> data)
        {
            _data = data;
            return this;
        }

        public BulkInsertBuilder<T> ToTable(string tableName)
        {
            _tableName = tableName;
            return this;
        }

        public BulkInsertBuilder<T> WithOuputId(string idColumn)
        {
            _ouputIdColumn = idColumn;
            return this;
        }

        public BulkInsertBuilder<T> WithOuputId(Expression<Func<T, object>> idSelector)
        {
            _ouputIdColumn = idSelector.Body.GetMemberName();
            return this;
        }

        public BulkInsertBuilder<T> WithColumns(IEnumerable<string> columnNames)
        {
            _columnNames = columnNames;
            return this;
        }

        public BulkInsertBuilder<T> WithColumns(Expression<Func<T, object>> columnNamesSelector)
        {
            _columnNames = columnNamesSelector.Body.GetMemberNames().ToArray();
            return this;
        }

        public BulkInsertBuilder<T> WithDbColumnMappings(IDictionary<string, string> dbColumnMappings)
        {
            _dbColumnMappings = dbColumnMappings;
            return this;
        }

        public BulkInsertBuilder<T> ConfigureBulkOptions(Action<BulkInsertOptions> configureOptions)
        {
            _options = new BulkInsertOptions();
            if (configureOptions != null)
            {
                configureOptions(_options);
            }
            return this;
        }

        private string GetDbColumnName(string columnName)
        {
            if (_dbColumnMappings == null)
            {
                return columnName;
            }

            return _dbColumnMappings.ContainsKey(columnName) ? _dbColumnMappings[columnName] : columnName;
        }

        public void Execute()
        {
            DataTable dataTable;
            if (string.IsNullOrWhiteSpace(_ouputIdColumn))
            {
                dataTable = _data.ToDataTable(_columnNames.ToList());

                _connection.EnsureOpen();

                Log($"Begin executing SqlBulkCopy. TableName: [{_tableName}]");
                dataTable.SqlBulkCopy(_tableName, _dbColumnMappings, _connection, _transaction, _options);
                Log("End executing SqlBulkCopy.");
                return;
            }

            if (_options.KeepIdentity)
            {
                var columns = _columnNames.Select(x => x).ToList();
                if (!columns.Contains(_ouputIdColumn))
                {
                    columns.Add(_ouputIdColumn);
                }

                dataTable = _data.ToDataTable(columns.ToList());

                _connection.EnsureOpen();

                Log($"Begin executing SqlBulkCopy. TableName: [{_tableName}]");
                dataTable.SqlBulkCopy(_tableName, _dbColumnMappings, _connection, _transaction, _options);
                Log("End executing SqlBulkCopy.");
                return;
            }

            var temptableName = "#" + Guid.NewGuid();
            dataTable = _data.ToDataTable(_columnNames.ToList(), addIndexNumberColumn: true);
            var sqlCreateTemptable = dataTable.GenerateTableDefinition(temptableName);

            var mergeStatementBuilder = new StringBuilder();
            mergeStatementBuilder.AppendLine($"MERGE INTO [{_tableName}]");
            mergeStatementBuilder.AppendLine("USING");
            mergeStatementBuilder.AppendLine("(");
            mergeStatementBuilder.AppendLine($"SELECT TOP {_data.Count()} * FROM [{temptableName}] ORDER BY [{Constants.AutoGeneratedIndexNumberColumn}]");
            mergeStatementBuilder.AppendLine(") AS Src");
            mergeStatementBuilder.AppendLine("ON 1 = 0");
            mergeStatementBuilder.AppendLine("WHEN NOT MATCHED BY TARGET THEN");
            mergeStatementBuilder.AppendLine($"INSERT ({string.Join(", ", _columnNames.Select(x => $"[{GetDbColumnName(x)}]"))})");
            mergeStatementBuilder.AppendLine($"VALUES ({string.Join(", ", _columnNames.Select(x => $"Src.[{x}]"))})");
            mergeStatementBuilder.AppendLine($"OUTPUT inserted.[{GetDbColumnName(_ouputIdColumn)}], Src.[{Constants.AutoGeneratedIndexNumberColumn}]");
            mergeStatementBuilder.AppendLine(";");

            _connection.EnsureOpen();

            Log($"Begin creating temp table:{Environment.NewLine}{sqlCreateTemptable}");
            using (var createTemptableCommand = _connection.CreateTextCommand(_transaction, sqlCreateTemptable))
            {
                createTemptableCommand.ExecuteNonQuery();
            }
            Log("End creating temp table.");

            Log($"Begin executing SqlBulkCopy. TableName: [{temptableName}]");
            dataTable.SqlBulkCopy(temptableName, null, _connection, _transaction, _options);
            Log("End executing SqlBulkCopy.");

            var returnedIds = new Dictionary<long, object>();

            var sqlMergeStatement = mergeStatementBuilder.ToString();

            Log($"Begin merging temp table:{Environment.NewLine}{sqlMergeStatement}");
            using (var updateCommand = _connection.CreateTextCommand(_transaction, sqlMergeStatement))
            {
                using var reader = updateCommand.ExecuteReader();
                var dbColumn = GetDbColumnName(_ouputIdColumn);
                while (reader.Read())
                {
                    returnedIds[(reader[Constants.AutoGeneratedIndexNumberColumn] as long?).Value] = reader[dbColumn];
                }
            }
            Log("End merging temp table.");

            var idProperty = typeof(T).GetProperty(_ouputIdColumn);

            long idx = 0;
            foreach (var row in _data)
            {
                idProperty.SetValue(row, returnedIds[idx]);
                idx++;
            }
        }

        private void Log(string message)
        {
            _options?.LogTo?.Invoke($"{DateTimeOffset.Now:yyyy-MM-dd HH:mm:ss.fff zzz} [BulkInsert]: {message}");
        }
    }
}
