using EntityFrameworkCore.SqlServer.SimpleBulks.Extensions;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Text;

namespace EntityFrameworkCore.SqlServer.SimpleBulks.BulkInsert
{
    public class BulkInsertBuilder<T>
    {
        private IEnumerable<T> _data;
        private string _tableName;
        private string _ouputIdColumn;
        private IEnumerable<string> _columnNames;
        private BulkOptions _options;
        private readonly SqlConnection _connection;
        private readonly SqlTransaction _transaction;

        public BulkInsertBuilder(SqlConnection connection)
        {
            _connection = connection;
        }

        public BulkInsertBuilder(SqlTransaction transaction)
        {
            _transaction = transaction;
            _connection = transaction.Connection;
        }

        public BulkInsertBuilder(SqlConnection connection, SqlTransaction transaction = null)
        {
            _connection = connection;
            _transaction = transaction;
        }

        public BulkInsertBuilder<T> WithData(IEnumerable<T> data)
        {
            _data = data;
            return this;
        }

        public BulkInsertBuilder<T> ToTable(string tableName)
        {
            _tableName = tableName;
            return this;
        }

        public BulkInsertBuilder<T> WithOuputId(string idColumn)
        {
            _ouputIdColumn = idColumn;
            return this;
        }

        public BulkInsertBuilder<T> WithOuputId(Expression<Func<T, object>> idSelector)
        {
            _ouputIdColumn = idSelector.Body.GetMemberName();
            return this;
        }

        public BulkInsertBuilder<T> WithColumns(IEnumerable<string> columnNames)
        {
            _columnNames = columnNames;
            return this;
        }

        public BulkInsertBuilder<T> WithColumns(Expression<Func<T, object>> columnNamesSelector)
        {
            _columnNames = columnNamesSelector.Body.GetMemberNames().ToArray();
            return this;
        }

        public BulkInsertBuilder<T> ConfigreBulkOptions(Action<BulkOptions> configureOptions)
        {
            _options = new BulkOptions();
            configureOptions(_options);
            return this;
        }

        public void Execute()
        {
            DataTable dataTable;
            if (string.IsNullOrWhiteSpace(_ouputIdColumn))
            {
                dataTable = _data.ToDataTable(_columnNames.ToList());

                _connection.EnsureOpen();
                dataTable.SqlBulkCopy(_tableName, _connection, _transaction, _options);
                return;
            }

            var temptableName = "#" + Guid.NewGuid();
            dataTable = _data.ToDataTable(_columnNames.ToList(), addIndexNumberColumn: true);
            var sqlCreateTemptable = dataTable.GenerateTableDefinition(temptableName, new[] { Constants.AutoGeneratedIndexNumberColumn });

            var mergeStatementBuilder = new StringBuilder();
            mergeStatementBuilder.AppendLine($"MERGE INTO [{_tableName}]");
            mergeStatementBuilder.AppendLine("USING");
            mergeStatementBuilder.AppendLine("(");
            mergeStatementBuilder.AppendLine($"SELECT TOP {_data.Count()} * FROM [{temptableName}] ORDER BY [{Constants.AutoGeneratedIndexNumberColumn}]");
            mergeStatementBuilder.AppendLine(") AS Src");
            mergeStatementBuilder.AppendLine("ON 1 = 0");
            mergeStatementBuilder.AppendLine("WHEN NOT MATCHED BY TARGET THEN");
            mergeStatementBuilder.AppendLine($"INSERT ({string.Join(", ", _columnNames.Select(x => $"[{x}]"))})");
            mergeStatementBuilder.AppendLine($"VALUES ({string.Join(", ", _columnNames.Select(x => $"Src.[{x}]"))})");
            mergeStatementBuilder.AppendLine($"OUTPUT inserted.[{_ouputIdColumn}], Src.[{Constants.AutoGeneratedIndexNumberColumn}]");
            mergeStatementBuilder.AppendLine(";");

            _connection.EnsureOpen();

            using (var createTemptableCommand = _connection.CreateTextCommand(_transaction, sqlCreateTemptable))
            {
                createTemptableCommand.ExecuteNonQuery();
            }

            dataTable.SqlBulkCopy(temptableName, _connection, _transaction, _options);

            var returnedIds = new Dictionary<long, object>();

            using (var updateCommand = _connection.CreateTextCommand(_transaction, mergeStatementBuilder.ToString()))
            {
                using (var reader = updateCommand.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        returnedIds[(reader[Constants.AutoGeneratedIndexNumberColumn] as long?).Value] = reader[_ouputIdColumn];
                    }
                }
            }

            var idProperty = typeof(T).GetProperty(_ouputIdColumn);

            long idx = 0;
            foreach (var row in _data)
            {
                idProperty.SetValue(row, returnedIds[idx]);
                idx++;
            }
        }

    }
}
