// <auto-generated />
using System;
using ConnectionExtensionsExamples;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConnectionExtensionsExamples.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20251112230349_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConnectionExtensionsExamples.Entities.CompositeKeyRow", b =>
                {
                    b.Property<int>("Id1")
                        .HasColumnType("int");

                    b.Property<int>("Id2")
                        .HasColumnType("int");

                    b.Property<int>("Column1")
                        .HasColumnType("int");

                    b.Property<string>("Column2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Column3")
                        .HasColumnType("datetime2");

                    b.HasKey("Id1", "Id2");

                    b.ToTable("CompositeKeyRows");
                });

            modelBuilder.Entity("ConnectionExtensionsExamples.Entities.ConfigurationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id1")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Key1");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SeasonAsInt")
                        .HasColumnType("int");

                    b.Property<int?>("SeasonAsString")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConfigurationEntries");
                });

            modelBuilder.Entity("ConnectionExtensionsExamples.Entities.Row", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Column1")
                        .HasColumnType("int");

                    b.Property<string>("Column2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Column3")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
